name: misspell

on:
  - push
  - workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: sobolevn/misspell-fixer-action@master
      with:
        options: '-rsvn source/docs'
        github_token: ${{ secrets.github_token }}
        locale: 'US'
        level: 'warning'
        reporter: 'github-pr-check'

    - uses: peter-evans/create-pull-request@v2.4.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Fixes by misspell-fixer'
        title: 'Typos fix by misspell-fixer'
